---
title       : GLES-Treffen am 05.05.2015
subtitle    : Fortschritt der Kandidatenstudie zur Europawahl 2014
author      : Reinhold Melcher und Maurice Meyer
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---

## Stand der Kandidatenstudie zum 05.05.2015

- Rückantwort von 170 Kandidaten
- Erinnerung versandt am 21.05.2015
- Korrekturmail am 26.05.2015

<iframe src="http://ultraunix.github.io/ruckTab/"></iframe>

--- .class

## Entwicklung des Rücklaufs im Zeitverlauf
<p><font size="4">Versand der Fragebögen am 23.03.2015</font></p>
<iframe src="http://ultraunix.github.io/lineGles0505/" name="line" frameborder="0"></iframe>

--- 

## Ausschöpfungsquote
<p><font size="4">Ausschöpfungsquote der gewählten und nichtgewählten Kandidaten nach Parteien</font></p>
<iframe src="http://ultraunix.github.io/BarGlesAusspfg0505/" name="line" frameborder="0"></iframe>

--- 

## Repräsentativität
<p><font size="4">Anteil der Kandidaten je Partei für Stichprobe und  Grundgesamtheit (Duncan-Index 5.65)</font></p>
<iframe src="http://ultraunix.github.io/BarGlesRep0505/" name="line" frameborder="0"></iframe>

--- 

## Repräsentativität der gewählten Kandidaten I
<p><font size="4">Anteil der gewählten Kandidaten je Partei für Stichprobe und  Grundgesamtheit (Duncan-Index 17.95)</font></p>
<iframe src="http://ultraunix.github.io/BarGlesGewPar/" name="line" frameborder="1"></iframe>

--- 

## Repräsentativität gewählte Kandidaten II
<p><font size="4">Anteil der gewählten Kandidaten nach Geschlecht für Stichprobe und  Grundgesamtheit (Duncan-Index 0.7)</font></p>
<iframe src="http://ultraunix.github.io/BarGlesGewGesch/" name="line" frameborder="0"></iframe>

--- 

## Repräsentativität gewählte Kandidaten III
<p><font size="4">Anteil der Kandidaten je Partei für Stichprobe und  Grundgesamtheit (Duncan-Index 5.65)</font></p>
<iframe src="http://ultraunix.github.io/BarGlesRep0505/" name="line" frameborder="0"></iframe>

--- 
